# Generated by Django 5.1.3 on 2024-12-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_sold',
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medicines.order')),
            ],
            bases=('medicines.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.sale'),
        ),
    ]
