# Generated by Django 5.1.3 on 2024-12-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_order_remove_sale_medicine_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
